development:
  adapter: mysql2
  encoding: utf8
  database: eSikke
  pool: 5
  username: eSikke
  password: doitnow1
  host: esikke.cnrhcqurfjvj.us-east-1.rds.amazonaws.com
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: eSikke
  pool: 5
  username: eSikke
  password: doitnow1
  host: esikke.cnrhcqurfjvj.us-east-1.rds.amazonaws.com
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: eSikke
  pool: 5
  username: eSikke
  password: doitnow1
  host: esikke.cnrhcqurfjvj.us-east-1.rds.amazonaws.com
  port: 3306